Update to Snort 2.9.5.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,7 +6,7 @@ AC_PREREQ(2.50)
 AM_CONFIG_HEADER(config.h)
 # When changing the snort version, please also update the VERSION
 # definition in "src/win32/WIN32-Includes/config.h"
-AM_INIT_AUTOMAKE(snort,2.9.4.6)
+AM_INIT_AUTOMAKE(snort,2.9.5)
 
 NO_OPTIMIZE="no"
 ADD_WERROR="no"
@@ -557,15 +557,6 @@ if test "x$SIGNAL_SNORT_READ_ATTR_TBL" != "x" ; then
    AC_DEFINE_UNQUOTED([SIGNAL_SNORT_READ_ATTR_TBL], [$SIGNAL_SNORT_READ_ATTR_TBL], [Set by user])
 fi
 
-AC_ARG_ENABLE(dynamicplugin,
-[  --disable-dynamicplugin  Disable Ability to dynamically load preprocessors, detection engine, and rules lib],
-       enable_dynamicplugin="$enableval", enable_dynamicplugin="yes")
-AM_CONDITIONAL(HAVE_DYNAMIC_PLUGINS, test "x$enable_dynamicplugin" = "xyes")
-
-if test "x$enable_dynamicplugin" = "xyes"; then
-    CPPFLAGS="$CPPFLAGS -DDYNAMIC_PLUGIN"
-fi
-
 AC_ARG_ENABLE(so_with_static_lib,
 [  --enable-so-with-static-lib  Enable linking of dynamically loaded preprocessors with a static preprocessor library],
        enable_so_with_static_lib="$enableval", enable_so_with_static_lib=$so_with_static_lib)
@@ -583,6 +574,20 @@ fi
 AM_CONDITIONAL(BUILD_CONTROL_SOCKET, test "x$enable_control_socket" = "xyes")
 if test "x$enable_control_socket" = "xyes"; then
     CONFIGFLAGS="$CONFIGFLAGS -DCONTROL_SOCKET"
+fi
+
+AC_ARG_ENABLE(side_channel,
+[  --enable-side-channel    Enable the side channel],
+       enable_side_channel="$enableval", enable_side_channel="no")
+if test "x$linux" != "xyes"; then
+    if test "x$enable_side_channel" = "xyes"; then
+        AC_MSG_WARN([[The side channel is only supported on Linux systems.]])
+        enable_side_channel="no"
+    fi
+fi
+AM_CONDITIONAL(BUILD_SIDE_CHANNEL, test "x$enable_side_channel" = "xyes")
+if test "x$enable_side_channel" = "xyes"; then
+    CONFIGFLAGS="$CONFIGFLAGS -DSIDE_CHANNEL"
 fi
 
 # check for dnet first since some DAQs need it
@@ -649,22 +654,18 @@ AC_ARG_ENABLE(static_daq,
 [  --disable-static-daq     Link static DAQ modules.],
        enable_static_daq="$enableval", enable_static_daq="yes")
 
-if test "x$enable_static_daq" = "xyes" \
-     -o "x$enable_dynamicplugin" = "xyes" ; \
-then
-    AC_CHECK_LIB(dl, dlsym, DLLIB="yes", DLLIB="no")
+AC_CHECK_LIB(dl, dlsym, DLLIB="yes", DLLIB="no")
 
-    if test "$DLLIB" != "no"; then
-        LIBS="${LIBS} -ldl"
-    else
-        AC_CHECK_LIB(c, dlsym, DLLIB="yes", DLLIB="no")
-        if test "$DLLIB" = "no"; then
-           echo
-           echo "   ERROR!  programmatic interface to dynamic link loader"
-           echo "   not found.  Cannot build Snort."
-           echo
-           exit 1
-        fi
+if test "$DLLIB" != "no"; then
+    LIBS="${LIBS} -ldl"
+else
+    AC_CHECK_LIB(c, dlsym, DLLIB="yes", DLLIB="no")
+    if test "$DLLIB" = "no"; then
+       echo
+       echo "   ERROR!  programmatic interface to dynamic link loader"
+       echo "   not found.  Cannot build Snort."
+       echo
+       exit 1
     fi
 fi
 
@@ -784,14 +785,6 @@ AC_ARG_ENABLE(build-dynamic-examples,
 [  --enable-build-dynamic-examples   Enable building of example dynamically loaded preprocessor and rule (off by default)],
        build_dynamic_examples="$enableval", build_dynamic_examples="no")
 AM_CONDITIONAL(BUILD_DYNAMIC_EXAMPLES, test "x$build_dynamic_examples" = "xyes")
-if test "x$build_dynamic_examples" = "xyes"; then
-    if test "x$enable_dynamicplugin" = "xno"; then
-       echo "   ERROR!  attempting to build dynamic examples without"
-       echo "   enabling dynamic plugins."
-       echo
-       exit 1
-    fi
-fi
 
 AC_ARG_ENABLE(dlclose,
 [  --disable-dlclose        Only use if you are developing dynamic preprocessors or shared object rules.  Disable (--disable-dlclose) for testing valgrind leaks in dynamic libraries so a usable backtrace is reported.  Enabled by default.],
@@ -998,12 +991,13 @@ if test "x$enable_reload" = "xyes"; then
     LIBS="$LIBS -lpthread"
 fi
 
-AC_ARG_ENABLE(paf,
-[  --disable-paf            Disable protocol aware flushing],
-       enable_paf="$enableval", enable_paf="yes")
+AC_ARG_ENABLE(ha,
+[  --enable-ha              Enable high-availability state sharing],
+       enable_ha="$enableval", enable_ha="no")
 
-if test "x$enable_paf" = "xyes"; then
-    CPPFLAGS="${CPPFLAGS} -DENABLE_PAF"
+AM_CONDITIONAL(BUILD_HA, test "x$enable_ha" = "xyes")
+if test "x$enable_ha" = "xyes"; then
+    CONFIGFLAGS="$CONFIGFLAGS -DENABLE_HA"
 fi
 
 # define NO_NON_ETHER_DECODERS by default
@@ -1248,7 +1242,7 @@ fi
 echo $CFLAGS > cflags.out
 echo $CPPFLAGS > cppflags.out
 
-INCLUDES='-I$(top_srcdir) -I$(top_srcdir)/src -I$(top_srcdir)/src/sfutil $(extra_incl) -I$(top_srcdir)/src/output-plugins -I$(top_srcdir)/src/detection-plugins -I$(top_srcdir)/src/dynamic-plugins -I$(top_srcdir)/src/preprocessors -I$(top_srcdir)/src/preprocessors/portscan -I$(top_srcdir)/src/preprocessors/HttpInspect/include -I$(top_srcdir)/src/preprocessors/Stream5 -I$(top_srcdir)/src/target-based -I$(top_srcdir)/src/control -I$(top_srcdir)/src/file-process -I$(top_srcdir)/src/file-process/libs'
+INCLUDES='-I$(top_srcdir) -I$(top_srcdir)/src -I$(top_srcdir)/src/sfutil $(extra_incl) -I$(top_srcdir)/src/output-plugins -I$(top_srcdir)/src/detection-plugins -I$(top_srcdir)/src/dynamic-plugins -I$(top_srcdir)/src/preprocessors -I$(top_srcdir)/src/preprocessors/portscan -I$(top_srcdir)/src/preprocessors/HttpInspect/include -I$(top_srcdir)/src/preprocessors/Stream5 -I$(top_srcdir)/src/target-based -I$(top_srcdir)/src/control -I$(top_srcdir)/src/file-process -I$(top_srcdir)/src/file-process/libs -I$(top_srcdir)/src/side-channel -I$(top_srcdir)/src/side-channel/plugins'
 
 AC_SUBST(INCLUDES)
 AC_SUBST(CONFIGFLAGS)
@@ -1264,6 +1258,10 @@ src/sfutil/Makefile \
 src/control/Makefile \
 src/file-process/Makefile \
 src/file-process/libs/Makefile \
+src/side-channel/Makefile \
+src/side-channel/dynamic-plugins/Makefile \
+src/side-channel/dynamic-plugins/snort_side_channel.pc  \
+src/side-channel/plugins/Makefile \
 src/detection-plugins/Makefile \
 src/dynamic-examples/Makefile \
 src/dynamic-examples/dynamic-preprocessor/Makefile \
